"""Event identity and grouping rules for Park-IO digest generation."""

from digest_config import OFFICIAL_CATEGORY_ORDER, SOURCE_AUTHORITY, SOURCE_ROLES


def normalized_topic_text(item: dict) -> str:
    values = [
        item.get("source", ""),
        item.get("title", ""),
        item.get("content", ""),
        " ".join(item.get("tags", [])),
    ]
    return " ".join(values).lower()


def source_role_for_item(item: dict) -> str:
    return SOURCE_ROLES.get(item.get("source", ""), "other")


def stable_item_key(item: dict) -> str:
    return item.get("url") or item.get("id") or item.get("title") or "unknown"


def is_manually_curated(item: dict) -> bool:
    return source_role_for_item(item) in {"user_saved", "wechat_article"}


def can_use_canonical_event_rules(item: dict) -> bool:
    role = source_role_for_item(item)
    source = item.get("source", "")
    return (
        role in {"company_official", "company_person"}
        or source in {"claude-code-releases", "openai-codex-releases"}
    )


def event_key(item: dict) -> str:
    text = normalized_topic_text(item)
    tags = item.get("tags", [])
    source = item.get("source", "")
    url = item.get("url", "")

    if is_manually_curated(item):
        return stable_item_key(item)

    if source == "claude-code-releases":
        return url or item.get("title") or "claude-code-release"
    if source == "openai-codex-releases":
        return url or item.get("title") or "openai-codex-release"

    if source in {"Claude Blog", "OpenAI Blog"}:
        return url or item.get("title") or "official-blog-post"

    if can_use_canonical_event_rules(item) and any(word in text for word in ("founder's playbook", "founders playbook", "ai-native startup", "ai native startup", "ai 创业手册", "创业手册")):
        return "claude-founders-playbook"

    if can_use_canonical_event_rules(item) and "openai" in text and any(
        word in text
        for word in (
            "guaranteed capacity",
            "capacity-constrained",
            "capacity constrained",
            "certainty on capacity",
            "long-term access",
            "discounted tokens",
            "1-3 year",
            "1–3 year",
            "compute-constrained",
            "compute constrained",
            "长期承诺",
            "容量保障",
            "算力保障",
            "计算资源",
        )
    ):
        return "openai-guaranteed-capacity"
    if can_use_canonical_event_rules(item) and "openai" in text and any(
        word in text
        for word in (
            "erdős",
            "erdos",
            "厄尔多斯",
            "unit distance",
            "planar unit distance",
            "combinatorial geometry",
            "discrete geometry",
            "geometry problem",
            "组合几何",
            "离散几何",
            "开放问题",
            "open problem",
            "math breakthrough",
            "数学突破",
        )
    ):
        return "openai-erdos-math-breakthrough"
    if can_use_canonical_event_rules(item) and "synthid" in text and ("openai" in text or "generated by openai" in text):
        return "openai-synthid-image-provenance"

    if can_use_canonical_event_rules(item) and ("anthropic" in text or "claude" in text):
        if "stainless" in text:
            return "anthropic-stainless-acquisition"
        if any(word in text for word in ("stainless", "sdk", "mcp", "claude code release", "claude-code-releases", "session resume", "/resume", "fast mode", "opus 4.7", "2.5", "agent sdk")):
            if any(word in text for word in ("usage credit", "usage credits", "extra usage", "额外使用", "使用额度", "spending limit", "auto-reload")):
                return "claude-usage-credits"
            if any(word in text for word in ("prompt cache", "prompt-cache", "cache diagnostics", "cache-diagnostics", "缓存诊断", "缓存未命中")):
                return "claude-prompt-cache-diagnostics"
            return "anthropic-claude-code-toolchain-update"
        if any(word in text for word in ("usage credit", "usage credits", "extra usage", "额外使用", "使用额度", "spending limit", "auto-reload")):
            return "claude-usage-credits"
        if any(word in text for word in ("prompt cache", "prompt-cache", "cache diagnostics", "cache-diagnostics", "缓存诊断", "缓存未命中")):
            return "claude-prompt-cache-diagnostics"
        if any(word in text for word in ("claude design", "design", "token limit", "tokens", "限额翻倍")):
            return "claude-design-token-limits"
    if can_use_canonical_event_rules(item) and "codex" in text and any(word in text for word in ("chatgpt", "mobile", "ios", "android", "anywhere", "phone", "手机", "移动", "远程")):
        return "openai-chatgpt-codex-mobile"
    if can_use_canonical_event_rules(item) and "claude" in text and ("code" in text or "agent sdk" in text):
        if any(word in text for word in ("limit", "limits", "quota", "credit", "pricing", "额度", "限额", "积分", "sdk")):
            return "claude-code-quota-access"
    if can_use_canonical_event_rules(item) and "opensquilla" in text:
        return "opensquilla-agent-cost-router"
    if can_use_canonical_event_rules(item) and "codex" in text and any(word in text for word in ("trial", "enterprise", "adopt", "free", "免费", "企业")):
        return "codex-enterprise-adoption"
    if can_use_canonical_event_rules(item) and "codex" in text and any(word in text for word in ("/goal", "persistent objective", "goal command", "目标")):
        return "codex-goal-command"
    if can_use_canonical_event_rules(item) and "codex" in text and "windows" in text and "sandbox" in text:
        return "codex-windows-sandbox"
    if can_use_canonical_event_rules(item) and ("claude for small business" in text or "small business" in text):
        return "claude-small-business"
    if can_use_canonical_event_rules(item) and "knowly" in text:
        return "knowly-content-tool"
    if source == "vista8" and "codex" in text and ("chrome" in text or "browser" in text or "插件" in text or "上架" in text):
        return "codex-chrome-extension-publishing"
    if SOURCE_ROLES.get(source) in {"application_practice", "creator_growth"} and "闲鱼" in text:
        return f"{source}:xianyu-practice"
    if SOURCE_ROLES.get(source) in {"application_practice", "creator_growth"}:
        return url or item.get("title") or "application-practice"
    return tags[0] if tags else (item.get("url") or item.get("title") or "unknown")


def source_rank(item: dict) -> int:
    return SOURCE_AUTHORITY.get(item.get("source", ""), 50)


def line_union(items: list[dict]) -> list[str]:
    order = ["development", "trading", "content"]
    seen = {line for item in items for line in item.get("line_fit", [])}
    return [line for line in order if line in seen]


def tags_union(items: list[dict]) -> list[str]:
    tags = []
    for item in items:
        for tag in item.get("tags", []):
            if tag not in tags:
                tags.append(tag)
    return tags[:4]


def conversation_counts(items: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for item in items:
        conv = item.get("conversation_id", "")
        if conv:
            counts[conv] = counts.get(conv, 0) + 1
    return counts


def build_events(items: list[dict], limit: int | None = 8, title_func=None) -> list[dict]:
    title_func = title_func or (lambda item: item.get("title", ""))
    # Same-thread tweets (>=2 in this batch sharing a conversation_id) merge into
    # one event (gotcha #9) — the parent tweet plus its replies. Standalone
    # tweets keep their normal event_key, so cross-source keyword merges are
    # unaffected (gotcha #10). Only fetches that captured conversation_id carry
    # it; older items have none and fall through unchanged.
    conv_counts = conversation_counts(items)
    buckets: dict[str, list[dict]] = {}
    for item in items:
        conv = item.get("conversation_id", "")
        if conv and conv_counts.get(conv, 0) >= 2:
            key = f"thread:{conv}"
        else:
            key = event_key(item)
        bucket = buckets.setdefault(key, [])
        if item.get("url") and any(existing.get("url") == item.get("url") for existing in bucket):
            continue
        bucket.append(item)

    events = []
    for key, group in buckets.items():
        group = sorted(
            group,
            key=lambda it: (-it.get("score", 3), -source_rank(it), it.get("title", "")),
        )
        primary = group[0]
        events.append(
            {
                "event_key": key,
                "items": group,
                "primary": primary,
                "score": max(it.get("score", 3) for it in group),
                "line_fit": line_union(group),
                "tags": tags_union(group),
            }
        )
    events.sort(
        key=lambda ev: (
            -ev["score"],
            -max(source_rank(it) for it in ev["items"]),
            title_func(ev["primary"]),
        )
    )
    if limit is None:
        return events
    return events[:limit]


def event_sources(event: dict) -> set[str]:
    return {item.get("source", "") for item in event.get("items", [])}


def source_role(name: str) -> str:
    return SOURCE_ROLES.get(name, "other")


def event_layer(event: dict) -> str:
    roles = {source_role(name) for name in event_sources(event)}
    if "longform_interview" in roles:
        return "长访谈 / 深度理解"
    if "user_saved" in roles:
        return "我的收藏"
    if "wechat_article" in roles:
        return "公众号文章"
    if roles & {"application_practice", "creator_growth"}:
        return "应用层实践"
    return "厂商动态"


def event_company(event: dict) -> str:
    source = event["primary"].get("source", "")
    if source in {"OpenAI X", "ChatGPT X", "OpenAI Blog", "OpenAI YouTube", "ChatGPT YouTube", "openai-codex-releases", "Sam Altman", "Greg Brockman", "Kevin Weil", "Mark Chen"}:
        return "OpenAI / ChatGPT / Codex"
    if source in {"Anthropic News", "Anthropic Engineering", "Claude Blog", "Anthropic X", "Claude X", "Claude Devs X", "Anthropic YouTube", "Claude YouTube", "claude-code-releases", "Dario Amodei", "Daniela Amodei", "Mike Krieger"}:
        return "Anthropic / Claude"
    text = normalized_topic_text(event["primary"]) + " " + " ".join(event.get("tags", []))
    key = event.get("event_key", "")
    if key.startswith("openai-") or "openai" in text or "chatgpt" in text or "codex" in text:
        return "OpenAI / ChatGPT / Codex"
    if "claude" in text or "anthropic" in text:
        return "Anthropic / Claude"
    if "google" in text or "gemini" in text:
        return "Google / Gemini"
    if "xai" in text or "grok" in text:
        return "xAI / Grok"
    if "meta" in text or "llama" in text:
        return "Meta / Llama"
    return "其他厂商"


def event_official_category(event: dict) -> str:
    key = event.get("event_key", "")
    text = normalized_topic_text(event["primary"]) + " " + " ".join(event.get("tags", []))
    source = event["primary"].get("source", "")
    if source in {"claude-code-releases", "openai-codex-releases"}:
        return "开发与集成层"
    if key in {
        "openai-chatgpt-codex-mobile",
        "codex-goal-command",
        "claude-design-token-limits",
        "claude-small-business",
    }:
        return "产品体验层"
    if key in {
        "anthropic-claude-code-toolchain-update",
        "anthropic-stainless-acquisition",
        "claude-prompt-cache-diagnostics",
        "codex-windows-sandbox",
    }:
        return "开发与集成层"
    if key in {"claude-usage-credits", "codex-enterprise-adoption", "openai-guaranteed-capacity"} or any(
        word in text for word in ("usage credit", "credits", "rate limit", "quota", "trial", "pricing", "计费", "额度", "限额", "免费试用", "企业试用")
    ):
        return "商业化与使用规则层"
    if any(word in text for word in ("model", "gpt-realtime", "realtime", "opus", "haiku", "sonnet", "性能", "速度", "latency", "上下文")):
        return "模型与性能层"
    if any(word in text for word in ("pwc", "stainless", "acquires", "acquisition", "partnership", "合作", "收购", "生态", "企业采用")):
        return "外部合作与生态信号"
    return "产品体验层"


def group_official_events_by_category(events: list[dict]) -> list[tuple[str, list[dict]]]:
    groups: dict[str, list[dict]] = {name: [] for name in OFFICIAL_CATEGORY_ORDER}
    for event in events:
        category = event_official_category(event)
        groups.setdefault(category, []).append(event)
    return [(name, groups[name]) for name in OFFICIAL_CATEGORY_ORDER if groups.get(name)]


def event_practice_group(event: dict) -> str:
    text = normalized_topic_text(event["primary"]) + " " + " ".join(event.get("tags", []))
    if any(word in text for word in ("xiaohongshu", "douyin", "content", "内容", "小红书", "抖音")):
        return "内容与分发实践"
    return "工具用法 / 产品实践"


def group_events_for_digest(events: list[dict]) -> list[tuple[str, list[dict]]]:
    order = [
        "厂商动态 / Anthropic / Claude",
        "厂商动态 / OpenAI / ChatGPT / Codex",
        "厂商动态 / Google / Gemini",
        "厂商动态 / xAI / Grok",
        "厂商动态 / Meta / Llama",
        "厂商动态 / 其他厂商",
        "我的收藏",
        "公众号文章",
        "应用层实践 / 工具用法 / 产品实践",
        "应用层实践 / 内容与分发实践",
    ]
    groups: dict[str, list[dict]] = {name: [] for name in order}
    for event in events:
        layer = event_layer(event)
        if layer == "厂商动态":
            key = f"{layer} / {event_company(event)}"
        elif layer == "应用层实践":
            key = f"{layer} / {event_practice_group(event)}"
        else:
            key = layer
        groups.setdefault(key, []).append(event)
    return [(name, groups[name]) for name in order if groups.get(name)]


def group_official_events(events: list[dict]) -> list[tuple[str, list[dict]]]:
    order = [
        "Anthropic / Claude",
        "OpenAI / ChatGPT / Codex",
        "Google / Gemini",
        "xAI / Grok",
        "Meta / Llama",
        "其他厂商",
    ]
    groups: dict[str, list[dict]] = {name: [] for name in order}
    for event in events:
        company = event_company(event)
        groups.setdefault(company, []).append(event)
    return [(name, groups[name]) for name in order if groups.get(name)]
