#!/usr/bin/env python3
"""
polish-douyin.py — Post-process a directory of douyin-downloader transcripts.

For each video subdirectory containing *.transcript.txt, this script:
  1. Reads the raw transcript (often traditional Chinese, no punctuation, one wall of text)
  2. Calls CLIProxyAPI to:
     - Convert traditional → simplified Chinese
     - Insert proper punctuation
     - Break into logical paragraphs (~150-300 chars each)
     - Preserve all original content (no summarization)
  3. Replaces the polished version into the corresponding .md archive (body only —
     the metadata header generated by ArchiveManager is preserved)
  4. Deletes the .mp4 video file (transcript is the canonical record)
  5. Keeps .transcript.txt, .transcript.json, _data.json for traceability

Usage:
  polish-douyin.py <root-dir>
  polish-douyin.py ~/park-io/library/profiles/manxue-ai/items/

Idempotent: a `.polished` marker file is written next to the .md;
re-runs skip already-polished videos.
"""
import json
import re
import sys
from pathlib import Path

from lib import LLMUnavailable, llm_call


POLISH_PROMPT = """你是一个中文转录后处理助手。我会给你一段从抖音/视频里转录出来的中文文本，原始转录有以下问题：

1. **可能是繁体中文**——你需要全部转成简体中文
2. **缺少标点符号**——你需要根据语义加上句号、逗号、问号、感叹号等
3. **是一个连贯的大段**——你需要按话题/逻辑切分成多个自然段落，每段 100-300 字

**严格要求**：
- 不要总结、不要省略、不要意译——保留原文每一个字的信息
- 只做：繁→简 + 加标点 + 分段。除此之外不要修改任何用词
- 段落之间用空行分隔（markdown 标准）
- 直接输出处理后的文本，不要前言、不要后记、不要 markdown 代码块包裹

下面是要处理的原始转录："""


def llm_polish(raw_text: str, max_tokens: int = 8000) -> str:
    return llm_call(POLISH_PROMPT + "\n\n" + raw_text, max_tokens=max_tokens, timeout=240)


def count_content_chars(text: str) -> int:
    """Count meaningful content characters — CJK ideographs + alphanumerics.
    Excludes punctuation, whitespace, and other formatting marks. Used to verify
    that polish didn't summarize / drop content."""
    return sum(
        1
        for c in text
        if ("一" <= c <= "鿿") or c.isalnum()
    )


# Polished version must retain at least this fraction of raw content chars.
# A drop below this threshold means the LLM summarized / abbreviated content,
# which violates verbatim guarantee — the polish is rejected.
VERBATIM_MIN_RATIO = 0.95


def _find_header_end(md_text: str) -> int:
    """Return char index where the archive's metadata header ends and the
    transcript body begins. We replace the transcript only, not the header.

    ArchiveManager format:
        # <title>
        <description lines (zero or more)>

        > Date: ... | Author: ... | URL: ... | ID: ...

        **标签:** #...

        <transcript body>            ← we replace from here onward
    """
    # Prefer cutting just after the **标签:** / **Tags:** line
    m = re.search(r"^\*\*(?:标签|Tags|tags)[^*]*\*\*[^\n]*", md_text, re.MULTILINE)
    if m:
        return m.end()
    # Fallback: cut just after the > metadata line
    m = re.search(r"^>[^\n]*", md_text, re.MULTILINE)
    if m:
        return m.end()
    # Last resort: keep only the first H1 line
    m = re.match(r"^#[^\n]*", md_text)
    if m:
        return m.end()
    return 0


def find_video_dirs(root: Path) -> list:
    """Find all subdirs containing *.transcript.txt (one dir per video)."""
    dirs = []
    for tx in root.rglob("*.transcript.txt"):
        dirs.append(tx.parent)
    return sorted(set(dirs))


def polish_video_dir(d: Path) -> dict:
    """Polish one video dir. Returns {status, message, paragraphs_before, paragraphs_after}."""
    marker = d / ".polished"
    if marker.exists():
        return {"status": "skip", "message": "already polished"}

    transcript_files = list(d.glob("*.transcript.txt"))
    if not transcript_files:
        return {"status": "skip", "message": "no transcript.txt"}
    txt_path = transcript_files[0]

    md_files = [
        m for m in d.glob("*.md") if not m.name.startswith(".")
    ]
    if not md_files:
        return {"status": "skip", "message": "no .md archive"}
    md_path = md_files[0]

    raw = txt_path.read_text(encoding="utf-8").strip()
    if not raw or raw.startswith("["):
        return {"status": "skip", "message": "transcript empty or error"}

    paragraphs_before = raw.count("\n\n") + 1

    try:
        polished = llm_polish(raw)
    except Exception as ex:
        return {"status": "error", "message": f"LLM call failed: {ex}"}

    if not polished:
        return {"status": "error", "message": "LLM returned empty"}

    # Verbatim guard: polished version must contain ≥ VERBATIM_MIN_RATIO of the
    # raw content chars. Anything less means the LLM summarized content — reject.
    raw_chars = count_content_chars(raw)
    polished_chars = count_content_chars(polished)
    if raw_chars > 0:
        ratio = polished_chars / raw_chars
        if ratio < VERBATIM_MIN_RATIO:
            return {
                "status": "error",
                "message": (
                    f"verbatim guard FAILED — polished kept "
                    f"{polished_chars}/{raw_chars} ({ratio:.0%}) of content chars; "
                    f"required ≥{int(VERBATIM_MIN_RATIO * 100)}%. Skipping (no .md change, no mp4 delete)."
                ),
            }

    paragraphs_after = polished.count("\n\n") + 1

    # Replace .md body — keep the metadata header (title, description, > metadata
    # line, **标签:** line); replace everything after with the polished transcript.
    original_md = md_path.read_text(encoding="utf-8")
    header_end = _find_header_end(original_md)
    new_md = original_md[:header_end].rstrip() + "\n\n" + polished + "\n"
    md_path.write_text(new_md, encoding="utf-8")

    # Delete .mp4 to save disk
    deleted = []
    for mp4 in d.glob("*.mp4"):
        try:
            mp4.unlink()
            deleted.append(mp4.name)
        except Exception:
            pass

    marker.write_text(
        json.dumps(
            {
                "polished_at_paragraphs": paragraphs_after,
                "deleted_mp4": deleted,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    return {
        "status": "ok",
        "message": f"{paragraphs_before}→{paragraphs_after} paragraphs, deleted {len(deleted)} mp4",
        "paragraphs_before": paragraphs_before,
        "paragraphs_after": paragraphs_after,
    }


def main(argv):
    if len(argv) < 2:
        print(f"Usage: {argv[0]} <root-dir>", file=sys.stderr)
        sys.exit(1)
    root = Path(argv[1]).expanduser()
    if not root.exists():
        print(f"Not found: {root}", file=sys.stderr)
        sys.exit(1)

    video_dirs = find_video_dirs(root)
    print(f"Found {len(video_dirs)} video dirs under {root}")

    ok = skip = err = 0
    for i, d in enumerate(video_dirs, 1):
        result = polish_video_dir(d)
        status = result["status"]
        rel = d.relative_to(root)
        print(f"[{i:3d}/{len(video_dirs)}] {status:5s} — {rel.name[:60]}: {result['message']}")
        if status == "ok":
            ok += 1
        elif status == "skip":
            skip += 1
        else:
            err += 1

    print(f"\nDone: ok={ok}, skip={skip}, err={err}")


if __name__ == "__main__":
    main(sys.argv)
