#!/usr/bin/env python3
"""Persist Twitter/X auth cookies for launchd runs.

Run manually from a logged-in desktop session when X cookies expire.
"""
import os
import stat
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "twitter-auth.env"
PYTHON = os.environ.get("PARKIO_TWITTER_PYTHON", str(Path.home() / ".local/share/uv/tools/twitter-cli/bin/python"))


def main() -> int:
    script = """
from twitter_cli.auth import get_cookies
c = get_cookies()
print(c.get("auth_token", ""))
print(c.get("ct0", ""))
"""
    result = subprocess.run(
        [PYTHON, "-c", script],
        capture_output=True,
        text=True,
        timeout=60,
    )
    if result.returncode != 0:
        print(result.stderr.strip())
        return result.returncode
    auth_token, ct0 = (result.stdout.splitlines() + ["", ""])[:2]
    if not auth_token or not ct0:
        print("missing auth_token or ct0")
        return 1

    tmp = OUT.with_suffix(".env.tmp")
    tmp.write_text(
        "\n".join(
            [
                "# Generated by refresh-twitter-auth.py. Do not commit.",
                f"TWITTER_AUTH_TOKEN={auth_token}",
                f"TWITTER_CT0={ct0}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    os.chmod(tmp, stat.S_IRUSR | stat.S_IWUSR)
    tmp.replace(OUT)
    os.chmod(OUT, stat.S_IRUSR | stat.S_IWUSR)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
